version: '3.4'
services:
  besu_node:
    image: hyperledger/besu:22.7.3-local
    command: ["--network=sepolia",
              "--data-path=/opt/besu/data/data",
              "--data-storage-format=BONSAI",
              "--host-allowlist=*",
              "--sync-mode=X_CHECKPOINT",
              "--rpc-http-enabled",
              "--rpc-http-cors-origins=*",
              "--fast-sync-min-peers=1",
              "--rpc-http-api=ADMIN,ETH,NET,WEB3",
              "--engine-host-allowlist=*",
              "--engine-jwt-secret=/secret/token.txt"]
    volumes:
      - ./secret:/secret
      - ./data/besu:/opt/besu/data
    ports:
      # Map the p2p port(30303) and RPC HTTP port(8545)
      - "8545:8545"
      - "30303:30303/tcp"
      - "30303:30303/udp"
  prysm_node:
    image: statusim/nimbus-eth2:amd64-latest
    command: ["--network=sepolia",
              "--data-dir=/opt/nimbus/data",
              "--web3-url=http://besu_node:8551",
              "--jwt-secret=/secret/token.txt"]
    volumes:
      - ./secret:/secret
      - ./data/nimbus:/opt/nimbus/data
    depends_on:
      - besu_node
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5051:5051"